---
title: "MATH/COSC 3570 - Introduction to Data Science"
tbl-colwidths: [5,10,30,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date        | Topic                                    |               To Do               |                                             Slides                                              |                                                                    Lab Exercise                                                                    |         Homework         |               Lab Presentation               |
|:-------:|---------|---------|:-------:|:--------:|:-------:|:-------:|:-------:|
|  1   | Tue, Jan 16 | Greetings + Overview of Data Science     | [📖](/weeks/week-1.html "Week 1") | [🖥️](/slides/01-syllabus.html "01-Syllabus") [🖥️](/slides/02-datascience.html "02-datascience") |                                                                                                                                                    |                          |                                              |
|      | Thu, Jan 18 | Posit Cloud and Git/GitHub Introduction  |                                   |                             [🖥️](/slides/03-posit.html "03-posit")                              |                          [📋](/exercise/lab00-posit.html "lab00-posit")[📋](/exercise/lab01-rscript.html "lab01-rscript")                          |                          |                                              |
|  2   | Tue, Jan 23 | Connecting Posit Cloud with GitHub       | [📖](/weeks/week-2.html "Week 2") |                               [🖥️](/slides/04-git.html "04-git")                                |                                                     [📋](/exercise/lab00-git.html "lab00-git")                                                     |                          |                                              |
|      | Thu, Jan 25 | Quarto                                   |                                   |                            [🖥️](/slides/05-quarto.html "05-quarto")                             | [📋](/exercise/lab02-quarto.html "lab02-quarto")[📋](/exercise/lab03-markdown.html "lab03-markdown")[📋](/exercise/lab04-chunk.html "lab04-chunk") |                          |                                              |
|  3   | Tue, Jan 30 | Quarto                                   |                                   |                                                                                                 |                                                                                                                                                    |                          |                                              |
|      | Thu, Feb 1  | R/Python Programming                     | [📖](/weeks/week-3.html "Week 3") |                            [🖥️](/slides/06-syntax.html "06-syntax")                             |                                                                                                                                                    |                          |                                              |
|  4   | Tue, Feb 6  | Python Programming                       |                                   |                                                                                                 |                               [📋](/exercise/lab05-rtype.html "lab05-rtype")[📋](/exercise/lab06-py.html "lab06-py")                               |                          |                                              |
|      | Thu, Feb 8  | R Tidyverse                              | [📖](/weeks/week-4.html "Week 4") |                           [🖥️](/slides/07-package.html "07-package")                            |                                                                                                                                                    | [✍️](/hw/hw1.html "hw1") |                                              |
|  5   | Tue, Feb 13 | Python Pandas/NumPy                      |                                   |                                                                                                 |                           [📋](/exercise/lab08-tibble.html "lab08-tibble")[📋](/exercise/lab09-numpy.html "lab09-numpy")                           |                          | [✅](/exercise/lab07-plot.html "lab07-plot") |
|      | Thu, Feb 15 | Data Importing                           | [📖](/weeks/week-5.html "Week 5") |                            [🖥️](/slides/08-import.html "08-import")                             |                                                  [📋](/exercise/lab10-import.html "lab10-import")                                                  |                          |                                              |
|  6   | Tue, Feb 20 | Data Visualization                       |                📖                 |                                               🖥️                                                |                                                                         📋                                                                         |                          |                                              |
|      | Thu, Feb 22 | Data Visualization                       |                                   |                                                                                                 |                                                                                                                                                    |                          |                                              |
|  7   | Tue, Feb 27 | Interactive Data Visualization           |                📖                 |                                               🖥️                                                |                                                                                                                                                    |                          |                      ✅                      |
|      | Thu, Feb 29 | Data Wrangling                           |                                   |                                               🖥️                                                |                                                                         📋                                                                         |                          |                                              |
|  8   | Tue, Mar 5  | Data Wrangling                           |                📖                 |                                               🖥️                                                |                                                                         📋                                                                         |                          |                                              |
|      | Thu, Mar 7  | Data Wrangling                           |                                   |                                               🖥️                                                |                                                                         📋                                                                         |            ✍️            |                                              |
|  9   | Tue, Mar 12 | ***NO CLASS: Spring break***             |                                   |                                                                                                 |                                                                                                                                                    |                          |                                              |
|      | Thu, Mar 14 | ***NO CLASS: Spring break***             |                                   |                                                                                                 |                                                                                                                                                    |                          |                                              |
|  10  | Tue, Mar 19 | Probabilistic and Statistical Simulation |                📖                 |                                               🖥️                                                |                                                                        📋📋                                                                        |                          |                                              |
|      | Thu, Mar 21 | Linear Regression                        |                                   |                                               🖥️                                                |                                                                                                                                                    |                          |                                              |
|  11  | Tue, Mar 26 | Linear Regression                        |                📖                 |                                                                                                 |                                                                         📋                                                                         |                          |                                              |
|      | Thu, Mar 28 | ***NO CLASS: Easter break***             |                                   |                                                                                                 |                                                                                                                                                    |                          |                                              |
|  12  | Tue, Apr 2  | Logistic Regression                      |                📖                 |                                               🖥️                                                |                                                                                                                                                    |                          |                                              |
|      | Thu, Apr 4  | Logistic Regression                      |                                   |                                                                                                 |                                                                         📋                                                                         |                          |                                              |
|  13  | Tue, Apr 9  | K-Nearest Neighbors                      |                📖                 |                                               🖥️                                                |                                                                                                                                                    |                          |                                              |
|      | Thu, Apr 11 | K-Nearest Neighbors                      |                                   |                                                                                                 |                                                                         📋                                                                         |            ✍️            |                                              |
|  14  | Tue, Apr 16 | Principal Component Analysis             |                📖                 |                                               🖥️                                                |                                                                                                                                                    |                          |                      📂                      |
|      | Thu, Apr 18 | Principal Component Analysis             |                                   |                                                                                                 |                                                                         📋                                                                         |                          |                                              |
|  15  | Tue, Apr 23 | K-Means Clustering                       |                📖                 |                                               🖥️                                                |                                                                                                                                                    |                          |                                              |
|      | Thu, Apr 25 | K-Means Clustering                       |                                   |                                                                                                 |                                                                         📋                                                                         |                          |                                              |
|  16  | Tue, Apr 30 | Data Dashboards                          |                📖                 |                                               🖥️                                                |                                                                                                                                                    |                          |                      📂                      |
|  16  | Thu, May 2  | Quarto Websites                          |                                   |                                                                                                 |                                                                                                                                                    |                          |                                              |
:::

I reserve the right to make changes to the schedule.

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
